chore: Update rust-toolchain (#106)
The older compiler is no longer working for some of our dependencies:

error: extern block cannot be declared unsafe
Error: -->
/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.75/src/backtrace/libunwind.rs:173:5